export const FETCH_USER = "FETCH_USER";

export const FETCH_BUDGETS = "FETCH_BUDGETS";
export const FETCH_BUDGET = "FETCH_BUDGET";
export const DELETE_BUDGET = "DELETE_BUDGET";

export const ADD_TRANSACTION = "ADD_TRANSACTION";
export const FETCH_TRANSACTION = "FETCH_TRANSACTION";

export const IS_LOADING = "IS_LOADING";
export const GET_ERROR = "GET_ERROR";
