export const FETCH_USER = 'FETCH_USER';
export const FETCH_BUDGETS = 'FETCH_BUDGETS';
export const FETCH_BUDGET = 'FETCH_BUDGET';
export const EDIT_BUDGET = 'EDIT_BUDGET';
export const DELETE_BUDGET = 'DELETE_BUDGET';
export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const DELETE_TRANSACTION = 'DELETE_TRANSACTION';
export const EDIT_TRANSACTION = 'EDIT_TRANSACTION';
