export const FETCH_USER = "FETCH_USER";

export const FETCH_BUDGETS = "FETCH_BUDGETS";
export const FETCH_BUDGET = "FETCH_BUDGET";

export const FETCH_TRANSACTION = "FETCH_TRANSACTION";

export const IS_LOADING = "IS_LOADING";
export const ON_FAILURE = "ON_FAILURE";
export const ON_SUCESS = "ON_SUCESS";

export const RESET_ON_SUCESS_MESSAGE = "RESET_ON_SUCESS_MESSAGE";
